---
- name: install mysql client
  yum: name=mysql
# setup cloud sql proxy
- name: check cloud sql proxy created ?
  stat: path=/usr/local/bin/cloud_sql_proxy
  register: cloudsqlproxy
- block:
    - get_url: url=https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 dest=/usr/local/bin/cloud_sql_proxy 
    - file: path=/usr/local/bin/cloud_sql_proxy mode="+x"
    - file: path=/cloudsql state=directory mode=0777
  when: not cloudsqlproxy.stat.exists
# start cloud sql proxy service
- block:
    - template: src=opt/cloud_sql_proxy.j2 dest=/opt/cloud_sql_proxy.sh mode="+x"
    - copy: src=etc/systemd/system/cloud_sql_proxy.service dest=/etc/systemd/system/cloud_sql_proxy.service
    - file: path=/var/log/cloud_sql_proxy.log state=absent
    - file: path=/var/log/cloud_sql_proxy.log owner=nginx group=nginx mode=0660 state=touch
    - command: systemctl start cloud_sql_proxy
    - command: systemctl enable cloud_sql_proxy
